resolver: lts-18.18
packages:
- '.'

extra-deps:
- unicode-data-0.3.0
- git: https://github.com/composewell/streamly
  commit: "4bb8b7c950ffeee9d5c9c3ca23c65be93ca34f0b"
- git: https://github.com/composewell/streamly
  commit: "4bb8b7c950ffeee9d5c9c3ca23c65be93ca34f0b"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
