resolver: lts-19.25

packages:
- .

extra-deps:
- unicode-data-0.3.0
- lockfree-queue-0.2.4
- github: composewell/streamly
  commit: "c2f79142411383e14d8c7db0f2456775549925f0"
- github: composewell/streamly
  commit: "c2f79142411383e14d8c7db0f2456775549925f0"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
