resolver: lts-19.25

packages:
- .

extra-deps:
- unicode-data-0.3.0
- lockfree-queue-0.2.4
- github: composewell/streamly
  commit: "e061109f76ef37a288de0cafa37ea950c467cb82"
- github: composewell/streamly
  commit: "e061109f76ef37a288de0cafa37ea950c467cb82"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
