resolver: lts-19.25

packages:
- .

extra-deps:
- unicode-data-0.3.0
- lockfree-queue-0.2.4
- github: composewell/streamly
  commit: "deb16f8670a4226f58177d8b1f0d6d840bff4dcd"
- github: composewell/streamly
  commit: "deb16f8670a4226f58177d8b1f0d6d840bff4dcd"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
