resolver: lts-20.14
packages:
- '.'
extra-deps:
- streamly-core-0.1.0
- streamly-0.9.0
- fusion-plugin-0.2.6

#- github: composewell/streamly
#  commit: "9596aea3ab33d3c2fa513247fcfe8604bd7ff454"
#- github: composewell/streamly
#  commit: "9596aea3ab33d3c2fa513247fcfe8604bd7ff454"
#  subdirs:
#    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
