resolver: lts-18.18
packages:
- '.'

extra-deps:
- unicode-data-0.2.0
- streamly-0.8.1

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
