resolver: lts-18.18
packages:
- '.'

extra-deps:
- unicode-data-0.3.0
- git: https://github.com/composewell/streamly
  commit: "cbccb7777792cb4bf8dd8716929f4e28ea6cf718"
- git: https://github.com/composewell/streamly
  commit: "cbccb7777792cb4bf8dd8716929f4e28ea6cf718"
  subdirs:
    - core

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
