# packcheck-0.7.0
# You can use any of the options supported by packcheck as environment
# variables here.  See https://github.com/composewell/packcheck for all
# options and their explanation.

name: packcheck

#-----------------------------------------------------------------------------
# Events on which the build should be triggered
#-----------------------------------------------------------------------------

on:
  push:
    branches:
      - master
  pull_request:


#-----------------------------------------------------------------------------
# Build matrix
#-----------------------------------------------------------------------------

jobs:
  build:
    name: ${{ matrix.name }}
    env:
      # ------------------------------------------------------------------------
      # Common options
      # ------------------------------------------------------------------------
      # GHC_OPTIONS: "-Werror"
      GHCUP_VERSION: 0.1.20.0
      DOCSPEC_URL: https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20210111/cabal-docspec-0.0.0.20210111.xz
      DOCSPEC_OPTIONS: "--timeout 60"
      CABAL_REINIT_CONFIG: y
      LC_ALL: C.UTF-8

      STACK_UPGRADE: "y"

      CABAL_CHECK_RELAX: y
      CABAL_HACKAGE_MIRROR: hackage.haskell.org:http://hackage.fpcomplete.com

      PACKCHECK: "./packcheck.sh"
      PACKCHECK_GITHUB_URL: "https://raw.githubusercontent.com/composewell/packcheck"
      PACKCHECK_GITHUB_COMMIT: "v0.7.0"

      BUILD: ${{ matrix.build }}
      GHCVER: ${{ matrix.ghc_version }}
      #RESOLVER: ${{ matrix.resolver }}
      CABAL_BUILD_OPTIONS: ${{ matrix.cabal_build_options }}
      CABAL_PROJECT: ${{ matrix.cabal_project }}
      #DISABLE_DOCS: ${{ matrix.disable_docs }}
      #DISABLE_SDIST_BUILD: ${{ matrix.disable_sdist_build }}
      #DISABLE_SDIST_BUILD: "y"
      HLINT_VERSION: 3.6.1
      HLINT_OPTIONS: ${{ matrix.hlint_options }}
      HLINT_TARGETS: ${{ matrix.hlint_targets }}

    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: 9.8.1-Werror
            ghc_version: 9.8.1
            build: cabal
            runner: ubuntu-latest
            cabal-version: 3.10.2.0
            cabal_project: cabal.project.d/master-Werror

          - name: 9.8.1-doctest
            runner: ubuntu-latest
            ghc_version: 9.8.1
            build: cabal
            cabal-version: 3.10.2.0
            cabal_project: cabal.project.d/master
            disable_test: "y"
            disable_bench: "y"
            disable_docs: "y"
            disable_sdist_build: "y"
            enable_docspec: "y"

          - name: hlint
            build: hlint
            hlint_options: "lint"
            hlint_targets: "src test Benchmark"
            runner: ubuntu-latest
            cabal-version: 3.2
            cabal_project: cabal.project.d/master

          - name: 9.6.3-macos
            runner: macos-latest
            ghc_version: 9.6.3
            build: cabal
            cabal-version: 3.10.1.0
            cabal_project: cabal.project.d/master

          - name: 9.4.4-streamly-0.9.0
            runner: ubuntu-latest
            ghc_version: 9.4.4
            build: cabal
            cabal-version: 3.8.1.0
            cabal_project: cabal.project.d/streamly-0.9.0

          - name: 9.4.4-streamly-0.10.0
            runner: ubuntu-latest
            ghc_version: 9.4.4
            build: cabal
            cabal-version: 3.8.1.0
            cabal_project: cabal.project.d/streamly-0.10.0

          - name: 9.2.7+fusion-plugin
            runner: ubuntu-latest
            ghc_version: 9.2.7
            build: cabal
            cabal-version: 3.6
            cabal_project: cabal.project.d/master
            cabal-build-options: --flag fusion-plugin

          - name: 8.10.7+macOS
            runner: macos-latest
            ghc_version: 8.10.7
            build: cabal
            cabal-version: 3.2
            cabal_project: cabal.project.d/master

          - name: 8.8.4
            runner: ubuntu-latest
            ghc_version: 8.8.4
            build: cabal
            cabal-version: 3.2
            cabal_project: cabal.project.d/master

          - name: 8.6.5
            runner: ubuntu-latest
            ghc_version: 8.6.5
            build: cabal
            cabal-version: 3.2
            cabal_project: cabal.project.d/master

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      name: Restore cache
      with:
        path: |
          ~/.local
          ~/.cabal
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.name }}

    - name: Download packcheck
      run: |
        # If a custom stack-yaml is specified, replace the default with that
        #if test -e "$STACK_YAML"; then rm -f stack.yaml && ln -sv $STACK_YAML stack.yaml; else true; fi
        #unset STACK_YAML

        if test ! -e "$PACKCHECK"
        then
          if test -z "$PACKCHECK_GITHUB_COMMIT"
          then
              die "PACKCHECK_GITHUB_COMMIT is not specified."
          fi
          PACKCHECK_URL=${PACKCHECK_GITHUB_URL}/${PACKCHECK_GITHUB_COMMIT}/packcheck.sh
          curl --fail -sL -o "$PACKCHECK" $PACKCHECK_URL || exit 1
          chmod +x $PACKCHECK
        elif test ! -x "$PACKCHECK"
        then
            chmod +x $PACKCHECK
        fi

    - name: Run packcheck
      run: |
          bash -c "$PACKCHECK $BUILD"
